require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ProviderSlugsController do

  # This should return the minimal set of attributes required to create a valid
  # ProviderSlug. As you add validations to ProviderSlug, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {  }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ProviderSlugsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all provider_slugs as @provider_slugs" do
      provider_slug = ProviderSlug.create! valid_attributes
      get :index, {}, valid_session
      assigns(:provider_slugs).should eq([provider_slug])
    end
  end

  describe "GET show" do
    it "assigns the requested provider_slug as @provider_slug" do
      provider_slug = ProviderSlug.create! valid_attributes
      get :show, {:id => provider_slug.to_param}, valid_session
      assigns(:provider_slug).should eq(provider_slug)
    end
  end

  describe "GET new" do
    it "assigns a new provider_slug as @provider_slug" do
      get :new, {}, valid_session
      assigns(:provider_slug).should be_a_new(ProviderSlug)
    end
  end

  describe "GET edit" do
    it "assigns the requested provider_slug as @provider_slug" do
      provider_slug = ProviderSlug.create! valid_attributes
      get :edit, {:id => provider_slug.to_param}, valid_session
      assigns(:provider_slug).should eq(provider_slug)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new ProviderSlug" do
        expect {
          post :create, {:provider_slug => valid_attributes}, valid_session
        }.to change(ProviderSlug, :count).by(1)
      end

      it "assigns a newly created provider_slug as @provider_slug" do
        post :create, {:provider_slug => valid_attributes}, valid_session
        assigns(:provider_slug).should be_a(ProviderSlug)
        assigns(:provider_slug).should be_persisted
      end

      it "redirects to the created provider_slug" do
        post :create, {:provider_slug => valid_attributes}, valid_session
        response.should redirect_to(ProviderSlug.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved provider_slug as @provider_slug" do
        # Trigger the behavior that occurs when invalid params are submitted
        ProviderSlug.any_instance.stub(:save).and_return(false)
        post :create, {:provider_slug => {  }}, valid_session
        assigns(:provider_slug).should be_a_new(ProviderSlug)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        ProviderSlug.any_instance.stub(:save).and_return(false)
        post :create, {:provider_slug => {  }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested provider_slug" do
        provider_slug = ProviderSlug.create! valid_attributes
        # Assuming there are no other provider_slugs in the database, this
        # specifies that the ProviderSlug created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        ProviderSlug.any_instance.should_receive(:update_attributes).with({ "these" => "params" })
        put :update, {:id => provider_slug.to_param, :provider_slug => { "these" => "params" }}, valid_session
      end

      it "assigns the requested provider_slug as @provider_slug" do
        provider_slug = ProviderSlug.create! valid_attributes
        put :update, {:id => provider_slug.to_param, :provider_slug => valid_attributes}, valid_session
        assigns(:provider_slug).should eq(provider_slug)
      end

      it "redirects to the provider_slug" do
        provider_slug = ProviderSlug.create! valid_attributes
        put :update, {:id => provider_slug.to_param, :provider_slug => valid_attributes}, valid_session
        response.should redirect_to(provider_slug)
      end
    end

    describe "with invalid params" do
      it "assigns the provider_slug as @provider_slug" do
        provider_slug = ProviderSlug.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ProviderSlug.any_instance.stub(:save).and_return(false)
        put :update, {:id => provider_slug.to_param, :provider_slug => {  }}, valid_session
        assigns(:provider_slug).should eq(provider_slug)
      end

      it "re-renders the 'edit' template" do
        provider_slug = ProviderSlug.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ProviderSlug.any_instance.stub(:save).and_return(false)
        put :update, {:id => provider_slug.to_param, :provider_slug => {  }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested provider_slug" do
      provider_slug = ProviderSlug.create! valid_attributes
      expect {
        delete :destroy, {:id => provider_slug.to_param}, valid_session
      }.to change(ProviderSlug, :count).by(-1)
    end

    it "redirects to the provider_slugs list" do
      provider_slug = ProviderSlug.create! valid_attributes
      delete :destroy, {:id => provider_slug.to_param}, valid_session
      response.should redirect_to(provider_slugs_url)
    end
  end

end
